#!/bin/bash
# wiki-loop2-report.sh
# Generate a 7-day effectiveness report for the Loop 2 Wiki Context Injector hook.
# Parses wiki/log/*.md, aggregates query injections, writes markdown report,
# pushes macOS notification (or logs to stdout on Linux).
#
# Run manually:  bash wiki-loop2-report.sh
# Run scheduled: via LaunchAgent (see launchagents/com.llm-wiki.loop2-weekly-report.plist)
#                or cron equivalent on Linux
#
# Configuration via environment variables:
#   WIKI_ROOT   — path to wiki directory (default: $HOME/wiki)
#   REPORT_DIR  — where to save reports (default: $WIKI_ROOT/reports)

set -euo pipefail

WIKI_ROOT="${WIKI_ROOT:-$HOME/wiki}"
LOG_DIR="$WIKI_ROOT/log"
REPORT_DIR="${REPORT_DIR:-$WIKI_ROOT/reports}"
TODAY=$(date +%Y-%m-%d)
REPORT_FILE="$REPORT_DIR/loop2-week1-${TODAY}.md"

mkdir -p "$REPORT_DIR"

# Collect log files from the last 7 days
LOG_FILES=()
for i in 0 1 2 3 4 5 6; do
    DATE_YMD=$(date -v-${i}d +%Y%m%d 2>/dev/null || date -d "$i days ago" +%Y%m%d)
    F="$LOG_DIR/${DATE_YMD}.md"
    [ -f "$F" ] && LOG_FILES+=("$F")
done

TMP=$(mktemp)
trap "rm -f $TMP" EXIT

# Extract all "query | Auto-injected" entries — python handles multibyte safely.
# Record delimiter is 0x1f (ASCII unit separator) since headers contain '|'.
python3 - "$TMP" "${LOG_FILES[@]+${LOG_FILES[@]}}" <<'PYEOF'
import sys, re, os
tmp_path = sys.argv[1]
files = sys.argv[2:]
header_re = re.compile(r'^## \[(\d+:\d+)\] query \| Auto-injected')
with open(tmp_path, 'w', encoding='utf-8') as out:
    for f in files:
        date = os.path.basename(f).replace('.md', '')
        with open(f, encoding='utf-8', errors='replace') as fh:
            lines = fh.readlines()
        i = 0
        while i < len(lines):
            m = header_re.match(lines[i])
            if m:
                header = lines[i].rstrip()
                matched = ''
                prompt = ''
                for j in range(i+1, min(i+6, len(lines))):
                    ln = lines[j].rstrip()
                    if ln.startswith('- Matched domains:'):
                        matched = ln
                    elif ln.startswith('- Prompt preview:'):
                        prompt = ln
                    elif ln.startswith('## '):
                        break
                out.write(f"{date}\x1f{header}\x1f{matched}\x1f{prompt}\n")
            i += 1
PYEOF

TOTAL_INJECTIONS=$(wc -l < "$TMP" | tr -d ' ')

# Domain frequency
DOMAIN_STATS=$(python3 - "$TMP" <<'PYEOF'
import sys, collections
c = collections.Counter()
with open(sys.argv[1], encoding='utf-8', errors='replace') as f:
    for line in f:
        parts = line.rstrip('\n').split('\x1f')
        if len(parts) < 3: continue
        m = parts[2].replace('- Matched domains:', '').strip()
        for d in [x.strip() for x in m.split(',') if x.strip()]:
            c[d] += 1
for d, n in c.most_common():
    print(f"{n}\t{d}")
PYEOF
)

# Daily breakdown
DAILY_STATS=$(python3 - "$TMP" <<'PYEOF'
import sys, collections
c = collections.Counter()
with open(sys.argv[1], encoding='utf-8', errors='replace') as f:
    for line in f:
        parts = line.split('\x1f', 1)
        if parts and parts[0]: c[parts[0]] += 1
for d, n in sorted(c.items()):
    print(f"- {d}: {n} injections")
PYEOF
)

# Sample prompts (most recent 10)
SAMPLE_PROMPTS=$(python3 - "$TMP" <<'PYEOF'
import sys
with open(sys.argv[1], encoding='utf-8', errors='replace') as f:
    lines = [l.rstrip('\n') for l in f][-10:]
for line in lines:
    parts = line.split('\x1f')
    if len(parts) < 4: continue
    date = parts[0]
    prompt = parts[3].replace('- Prompt preview:', '').strip()
    domain = parts[2].replace('- Matched domains:', '').strip()
    print(f"- `[{date}]` {prompt} → `{domain}`")
PYEOF
)

# Approximate token cost (based on observed avg of 1100 tokens per injection)
AVG_TOKENS_PER_INJECTION=1100
EST_DAILY_TOKENS=$((TOTAL_INJECTIONS * AVG_TOKENS_PER_INJECTION / 7))
EST_WEEKLY_TOKENS=$((TOTAL_INJECTIONS * AVG_TOKENS_PER_INJECTION))

# Write report
cat > "$REPORT_FILE" <<EOF
---
type: automation-report
date: $TODAY
period: 7-day Loop 2 observation
---
# Loop 2 Wiki Context Injector — Week 1 Report

> Auto-generated by \`wiki-loop2-report.sh\` on $TODAY

## TL;DR

- **Total injections (7 days):** $TOTAL_INJECTIONS
- **Avg injections/day:** $(echo "scale=1; $TOTAL_INJECTIONS / 7" | bc -l 2>/dev/null || echo "N/A")
- **Estimated context cost:** ~$EST_WEEKLY_TOKENS tokens this week (~$EST_DAILY_TOKENS /day)

## Daily Breakdown

$DAILY_STATS

## Domain Hit Distribution

\`\`\`
$DOMAIN_STATS
\`\`\`

## Recent Injection Samples

$SAMPLE_PROMPTS

## Assessment Checklist

- [ ] **Hit rate reasonable?** Expected 20-40% of domain-related prompts.
- [ ] **No false positives in samples?** If domain hit for off-topic prompts, tighten regex.
- [ ] **All domains getting hits?** Zero-hit domains may have overly specific keywords.
- [ ] **Token cost acceptable?** If weekly > 100K tokens, tighten per-domain head limit.
- [ ] **Wiki reference rate in responses ↑?** Manual check — count \`[[wikilinks]]\` in 5 recent responses.

## Phase 2 Candidates

1. **Page-title level matching** — if domain-level injection isn't precise enough
2. **Add missing domains** — if frequently unmatched questions span a new area
3. **Tune per-domain head limits** — per observed token distribution
4. **Opt-out logging** — log skip reasons to measure true opt-out rate

## Raw Data

Full log files: \`$LOG_DIR/\`

EOF

# Push notification (macOS terminal-notifier if available; falls back to stdout)
if command -v terminal-notifier >/dev/null 2>&1; then
    terminal-notifier \
        -title "LLM Wiki · Loop 2 Week 1 Report" \
        -subtitle "$TOTAL_INJECTIONS injections over 7 days" \
        -message "Report saved. Tap to open." \
        -sound Ping \
        -open "file://${REPORT_FILE// /%20}" >/dev/null 2>&1 || true
elif command -v notify-send >/dev/null 2>&1; then
    notify-send "LLM Wiki · Loop 2 Week 1 Report" "$TOTAL_INJECTIONS injections over 7 days"
fi

echo "✓ Report generated: $REPORT_FILE"
echo "  Total injections: $TOTAL_INJECTIONS"
echo "  Est. weekly tokens: ~$EST_WEEKLY_TOKENS"

exit 0
